#!/bin/bash

echo `date "+%F %T"`

if  [ "$1" == "clean" ]   ;then
    rm -rf ./build/*
    touch *.cpp
    touch *.h
	exit
fi

[ -d  ./build  ] ||  mkdir ./build
cd build
cmake ../

if  [ "$?" != "0" ]   ;then
    rm -rf ./build/*
else
    make -j 4
    cp ./generator_unittest ../
    cp ./interface_unittest ../
    rm -rf ../log/*
fi
